### PR TITLE
Trying to make shiny app and fixed a data typo

### PR DESCRIPTION
**Pull request by SamStruthers**
Found a small typo in site_code for a couple sites, fixed and re ran code to get cleaned file up to date and corrected. 
Have new dataset from Tim and will re release corrected dataset when that data are ready. 

Shiny app development starting. Make a basic app where you can select sites, dates and parameter you want to plot. You can also download the dataset you select (Need to make a function where you can download the whole dataset from Zenodo rather than this)

Runs just fine on my local computer but I get the following error when I try to deploy it to shiny: https://sam-struthers001.shinyapps.io/CPF_study_data_tester/
An error has occurred

The application failed to start.

exit status 1

### CODE REVIEW

**Comment by steeleb** [comment]
Hey @SamStruthers, can I help at all with review here? Looks like you fixed the deployment issue. Let me know if I can help get this merged to main.

**Comment by SamStruthers** [comment]
Updated data from new push from RMRS lab (20230925). Updated filenames and paths in readme/ 01_clean script so cleaned file is up to date. Finalized demo.R, which now works and shows how to download the folder from zenodo directly in R. 

Fixed the shiny app so it runs now. @steeleb, should this shiny app be moved to another repo so that it doesn't mess with zenodo pub?

**Comment by steeleb** [comment]
Heya @SamStruthers - the app looks GREAT! Can I request that the y axis adds the units for the parameters?

And yes, I think the original idea was that this repo was only for raw data, data processing, and QAQC'd data. It wouldn't necessarily mess up the pub, but it could complicate it. If it would make sense to bundle the Shiny app with these data (i.e., that app will only ever have these data in it), I think there is merit to keeping it here. It's functional, so I don't see a reason to not include it now if it will be included later.

**Comment by steeleb** [comment]
Oh, you should also add issue #2 in the 'Development' area on the RHS of this PR so that it will close with the close of this PR!

**Comment by SamStruthers** [comment]
Tried to solve the y axis issue but ended up breaking the multiple plot part of the app. I removed the shiny app code from the repo (will work on separate branch for a bit trying to fix it). I also fixed the filepath for the demo script. 

Just a quick review of the readme would be helpful to make sure that everything still makes sense :)
Then I'll merge this PR and release to Zenodo

**Review by steeleb — APPROVED** [review]
Metadata looks great!!

**Pull request merged**
